### ISSUE TITLE
Renamings

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#527]
We should start cleaning up some of the names.

Approach I recommend for discussion: top post contains consensus. Below we can add discussion for suggestions. Once we have consensus on new name, we add the change to the top post. Once the rename is complete (in a PR), we check it off the list.

Please add more suggestions for things to rename. Let’s just keep this issue going until we finish 1.0.

- [x]  `LiveVisualization` (see also #326) -> `StepVisualizer2D` #596
- [x] `Trajectory.md` -> `Trajectory.mdtraj` for clarity
- [x]  `SingleTrajectoryAnalysis` -> `TrajectoryTransitionAnalysis` #547
- [x]  `PathMoveChange` -> `MoveChange` #540 
- [x]  `spatial` and `atoms` (in features): add `n_` #531 
- [x] `nsteps_per_frame` -> `n_steps_per_frame` (in engine options) #531 
- [x] `CVRangeVolume`, `CVRangeVolumePeriodic` -> `CVDefinedVolume`, `PeriodicCVDefinedVolume` #543 
- [x] all CVs from `CV_Name` to `NameCV` to be consistant with other OPS objects naming #535 
- [x] `allow_partial` -> `allow_incomplete` (in storage) #534 
- [x] `global_state` (I found this quite long and not clear) maybe to `replica_state` or `sampleset` or `sample_state` -> `sample_set` #542 
- [x] `current_snapshot` for engine, there is always only the current snapshot, just call it `snapshot` -> keep the way it is
- [x] tests to start with `test_` (moved to #590)
- [x] `visualize_frequency` (in `PathSampling`) => `status_update_frequency` #596
- [x] `SampleSet.apply_samples` -> `.apply` or `.update` (which is more similar to python set.update). Also we use it with MoveChanges and Sample/SampleSets

**Comment by dwhswenson** [comment]
My first suggestions for fixes (don't have suggestions for everything yet):

* `spatial` and `atoms` => `n_spatial`, `n_atoms` 
* `nsteps_per_frame` => `n_steps_per_frame`

**Comment by jchodera** [comment]
`LiveVisualization` presumably only applies to 2D projections, right? Perhaps the new name should indicate that?

**Comment by dwhswenson** [comment]
> `LiveVisualization` presumably only applies to 2D projections, right? Perhaps the new name should indicate that?

I agree. Maybe `MCStep2DVisualizer`? The point is that it takes an MC step, and plots the move done in that step. The visualization changes depending on whether the move was accepted or not.

(OTOH, I think that `PathSampling.live_visualization` should keep the same name. The point is that the `LiveVisualization` object isn't only for use in the `live_visualization` variable!)

***

Also, added a new one above: `CVRangeVolume`. The problem is that this is too close to our naming convention for `CV_Function`, etc. To us it is obvious, since they're in different files. But to a user, they're both in the `openpathsampling` namespace, and share a prefix (the difference of the underscore is pretty subtle). We should either change the CVs to end with CV, or (my preference), change the `CVRangeVolume` to something that doesn't either begin or end with CV. `RangeCVVolume` isn't pretty, but would avoid the problem. Better ideas would be very welcome. (`PhaseSpaceCVVolume`? even just `PhaseSpaceVolume`? but neither of those are exactly accurate)

**Comment by dwhswenson** [comment]
Maybe `allow_partial` => `allow_incomplete`? It seems to me like partial here is the opposite of `complete`, is that correct?

My concern is that `allow_partial` isn't so obviously connected to what is "partial" about it. If a user made a complicated CV (e.g., one that returned an array -- possible now, right?), then `allow_partial` could be misunderstood as "part of the array."

**Comment by dwhswenson** [comment]
> all CVs from `CV_Name` to `NameCV` to be consistant with other OPS objects naming

Agreed. @jhprinz : do you want to make a PR for this one?

**Comment by jhprinz** [comment]
Sure. If you want to do it now. Please do so.

**Comment by jhprinz** [comment]
I can do the change for _numbers_of_ to `n_...` in a quick PR. I would prefer to leave dimension names as `atoms`, `spatial` because `netcdf+` uses `_` to separate object and attribute. Also, a dimension is always a number and this is kind of weird.

**Comment by dwhswenson** [comment]
>  I would prefer to leave dimension names as `atoms`, `spatial` because `netcdf+` uses _ to separate object and attribute. Also, a dimension is always a number and this is kind of weird.

But the point is that it isn't always totally obvious that these are dimensions (unless argument names are given explicitly). In particular, `atoms` can just as easily apply to a list of specific atom objects (and often does in, e.g., MDTraj!) It's also strange that we have a single inconsistency in nomenclature when dealing with internal storage aspects of netcdf+. Everywhere else we use `n_`; except this one place.

Is it possible to have the user-facing labels have the `n` prefix, and strip that internally in netcdf+?

**Comment by jhprinz** [comment]
> Is it possible to have the user-facing labels have the n prefix, and strip that internally in netcdf+?

I think so. Currently this is handles by the engine. It is resposible to provide properties to get the dimensions.

Actually. Now that I think of it, we can use dimension names including `n_...` that should not be a problem. It is kind of redundant to have `netcdf_file.dimensions = ['n_atoms', 'n_spatial', ...]` but who cares...

**Comment by jhprinz** [comment]
> Also, added a new one above: CVRangeVolume.

Would renaming the CVs to `...CV` fix this? Or is this still confusing. If we strictly have the type at the end that might be okay.

**Comment by jhprinz** [comment]
> `allow_incomplete`

I like that that will make a PR

**Comment by dwhswenson** [comment]
> Would renaming the CVs to `...CV` fix this?

Sort of. It definitely resolves the confusion I was most concerned about. But I still think the name is a bit unclear. What about `CVBasedVolume` or `CVDefinedVolume` or `SingleCVVolume`?

**Comment by dwhswenson** [comment]
#### `global_state`

Agree that this should change. I think I like `sampleset` most of the options. Key point to remember: even though this always represents the current state of the system, the user mainly sees it when setting initial conditions. So I think `sampleset=initial_conditions` reads best of the suggestions.

**Comment by dwhswenson** [comment]
Skype with @jhprinz : `SingleTrajectoryAnalysis` => `TrajectoryTransitionAnalysis` (and I'll do the PR to change that)

**Comment by dwhswenson** [comment]
#### `visualize_frequency`

This actually controls both the `PathSampling.live_visualization` and the step-by-step output of step number, which @jhprinz recently extended to add an estimated time remaining.

In an ipynb, it's great at every step. But in the output from a pure-Python run, you'll want less frequent updates. And since it isn't just for the visualization, let's give it a better name.

Maybe `status_update_frequency` or just `status_frequency`?

**Comment by jhprinz** [comment]
I just looked at this again. Maybe we should try not to make the visualization explicitly a part of the PathSampling, but rather an optional component that has access to the current status. Like adding a logger. We could provide several events and you can add an eventlistener that is called when something is happening. 

This would mean that the frequency would be part of the `LiveVisualization` object and not the PathSampling. 

```py
lv = LiveVisualization
Pathsampling.add_event_listener('update', lv)
```

That makes it very flexible to add more output for all sorts of purposes. Can be past 1.0.

**Comment by dwhswenson** [comment]
> Maybe we should try not to make the visualization explicitly a part of the PathSampling, but rather an optional component that has access to the current status.

I like this idea; I think it should wait for after `1.0`. I agree that this is a better and more flexible approach. But not worth cleaning up on a short timeframe.

**Comment by dwhswenson** [comment]
With #596 merged, all the tasks in this issue are completed. Closing it; we can always do another round of renaming later!

(Also, I really like the way this renaming issue went: the top post is a great record of what changes were made, and in what PR they occurred. Really useful when trying to fix work from other projects.)
